general:
  auto-splitter: <path>/autosplitter.wasm

  layout: <path>/layout.ls1l

  splits: <path>/splits.lss

  # comparison: Average Segments

  timing-method: GameTime

window:
  # width: 1500
  # height: 50
  always-on-top: true
  transparency: true
  # fps: 40

hotkeys:
#   split: Space
#   undo_all_pauses: NumPad7
#   toggle_timing_method: NumPad9

# connections:
  # twitch: puttheaccesstokenhere

# log:
#  path: log.txt
#  level: info
#  clear: true
